### ISSUE TITLE
onnxruntime_go 这个依赖包中所有的 Go 文件都被排除了

### ISSUE THREAD

**Issue by lin2574289184** [yatori-dev/yatori-go-console#35]
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\Yi\go #gosetup
"C:\Program Files\Go\bin\go.exe" build -o C:\Users\Yi\AppData\Local\JetBrains\GoLand2024.3\tmp\GoLand\___go_build_main_go.exe D:\yatori-go-console-main\main.go #gosetup
github.com/yalue/onnxruntime_go: build constraints exclude all Go files in C:\Users\Yi\go\pkg\mod\github.com\yalue\onnxruntime_go@v1.12.1

Compilation finished with exit code 1
![屏幕截图 2024-12-18 172555](https://github.com/user-attachments/assets/65f4236e-1e62-47cd-8883-cde32b801025)

**Comment by Changbaiqi** [comment]
你没打开CGO，onnx需要使用到CGO，这需要你先手动设置环境当前go的环境变量的CGO为打开状态

**Comment by Changbaiqi** [comment]
> GOROOT=C:\Program Files\Go #gosetup GOPATH=C:\Users\Yi\go #gosetup "C:\Program Files\Go\bin\go.exe" build -o C:\Users\Yi\AppData\Local\JetBrains\GoLand2024.3\tmp\GoLand___go_build_main_go.exe D:\yatori-go-console-main\main.go #gosetup github.com/yalue/onnxruntime_go: build constraints exclude all Go files in C:\Users\Yi\go\pkg\mod\github.com\yalue\onnxruntime_go@v1.12.1
> 
> Compilation finished with exit code 1 ![屏幕截图 2024-12-18 172555](https://private-user-images.githubusercontent.com/108447420/396843231-65f4236e-1e62-47cd-8883-cde32b801025.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTQ0NDMsIm5iZiI6MTczNDUxNDE0MywicGF0aCI6Ii8xMDg0NDc0MjAvMzk2ODQzMjMxLTY1ZjQyMzZlLTFlNjItNDdjZC04ODgzLWNkZTMyYjgwMTAyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwOTI5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTVkZmYzNTQzZWUyNmZlMGQ1Y2ZhYmY2M2JmNDg4MGI1NzA1YjVhNWQ2ODAxMDFhNjkwMzU5M2ZkNzZiMWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TSq7w3s8VsKbVdAk2CjBY59jxBN5100-5hi4V-ESnFU)

你没打开CGO，onnx需要使用到CGO，这需要你先手动设置环境当前go的环境变量的CGO为打开状态
